grpc:
  host: 'localhost'
  port: 8085

rabbit:
  protocol: amqp
  hostname: localhost
  username: guest
  password: guest
  port: 5672
  heartbeat: 1
  onConnectionEvent:
    exitOnClose: false
    exitOnError: false
  onChannelEvent:
    exitOnClose: false
    exitOnError: false
  retry:
    # forever: true
    retries: 5
    factor: 1
    minTimeout: 3000
    maxTimeout: 20000
typeOrm:
  type: postgres
  host: localhost
  username: giangnt
  password: giangnt
  port: 5432
  synchronize: true
  autoLoadEntities: true
  database: seed
  logging: true
mongoose:
  username: guest
  password: guest
  uri: mongodb://localhost:27017/seed
  host: localhost
  port: 27017
  database: microservices

redis:
  url: localhost
  password: null
  socket:
    port: 6379
    connectTimeout: 60000
  database: 1

throttler:
  - name: short
    ttl: 1000
    limit: 3
  - name: medium
    ttl: 10000
    limit: 20
  - name: long
    ttl: 60000
    limit: 100

mailConsume:
  sendMail:
    queue: notification_send_mail
    prefetchCount: 1
    queueType: quorum
    exchange: notification
    routingKey: notification_send_mail
    retryTime: 3000
    maxRetries: 1

kafka:
  clientId: my-app
  brokers:
    - localhost:9092

seedJob:
  type: SEED_JOB
  concurrent: 1
  enable: true
