/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace com {
    export namespace example {
        export namespace myservice {
            export interface MyMessage {
                name?: string;
                id?: number;
            }
        }
    }
}
